var annotated_dup =
[
    [ "OpenCascade", "namespace_open_cascade.html", "namespace_open_cascade" ],
    [ "AssLegFunction", "class_ass_leg_function.html", "class_ass_leg_function" ],
    [ "BEMFMA", "class_b_e_m_f_m_a.html", "class_b_e_m_f_m_a" ],
    [ "BEMProblem", "class_b_e_m_problem.html", "class_b_e_m_problem" ],
    [ "BoatModel", "class_boat_model.html", "class_boat_model" ],
    [ "BoatSurface", "class_boat_surface.html", "class_boat_surface" ],
    [ "ComputationalDomain", "class_computational_domain.html", "class_computational_domain" ],
    [ "ConstrainedMatrixBlock", "class_constrained_matrix_block.html", null ],
    [ "ConstrainedOperator", "class_constrained_operator.html", "class_constrained_operator" ],
    [ "DAETimeIntegrator", "class_d_a_e_time_integrator.html", "class_d_a_e_time_integrator" ],
    [ "Driver", "class_driver.html", "class_driver" ],
    [ "FreeSurface", "class_free_surface.html", "class_free_surface" ],
    [ "JacobianOperator", "class_jacobian_operator.html", "class_jacobian_operator" ],
    [ "LocalExpansion", "class_local_expansion.html", "class_local_expansion" ],
    [ "LocalExpansionCoeff", "class_local_expansion_coeff.html", "class_local_expansion_coeff" ],
    [ "MultipoleExpansion", "class_multipole_expansion.html", "class_multipole_expansion" ],
    [ "NewtonArgument", "class_newton_argument.html", "class_newton_argument" ],
    [ "NewtonSolver", "class_newton_solver.html", "class_newton_solver" ],
    [ "NumericalTowingTank", "class_numerical_towing_tank.html", "class_numerical_towing_tank" ],
    [ "OctreeBlock", "class_octree_block.html", "class_octree_block" ],
    [ "OdeArgument", "class_ode_argument.html", "class_ode_argument" ],
    [ "PreconditionerOperator", "class_preconditioner_operator.html", "class_preconditioner_operator" ],
    [ "ProblemInterface", "class_problem_interface.html", "class_problem_interface" ],
    [ "RestartNonlinearProblemAlg", "class_restart_nonlinear_problem_alg.html", "class_restart_nonlinear_problem_alg" ],
    [ "RestartNonlinearProblemDiff", "class_restart_nonlinear_problem_diff.html", "class_restart_nonlinear_problem_diff" ],
    [ "SurfaceSmoothing", "class_surface_smoothing.html", "class_surface_smoothing" ]
];