var modules =
[
    [ "Derived matrices", "group___matrix2.html", "group___matrix2" ],
    [ "Boundary and manifold description for triangulations", "http://www.dealii.org/developer/doxygen/deal.II/group__boundary.html", "group__boundary" ],
    [ "deal.II and the C++11 standard", "http://www.dealii.org/developer/doxygen/deal.II/group__CPP11.html", "group__CPP11" ],
    [ "Concepts, or expectations on template parameters", "http://www.dealii.org/developer/doxygen/deal.II/group__Concepts.html", null ],
    [ "Constraints on degrees of freedom", "http://www.dealii.org/developer/doxygen/deal.II/group__constraints.html", "group__constraints" ],
    [ "Parallel computing with multiple processors using distributed memory", "http://www.dealii.org/developer/doxygen/deal.II/group__distributed.html", "group__distributed" ],
    [ "Degrees of Freedom", "http://www.dealii.org/developer/doxygen/deal.II/group__dofs.html", "group__dofs" ],
    [ "Exceptions and assertions", "http://www.dealii.org/developer/doxygen/deal.II/group__Exceptions.html", "group__Exceptions" ],
    [ "Finite elements", "http://www.dealii.org/developer/doxygen/deal.II/group__feall.html", null ],
    [ "Base classes", "http://www.dealii.org/developer/doxygen/deal.II/group__febase.html", "group__febase" ],
    [ "Finite element access/FEValues classes", "http://www.dealii.org/developer/doxygen/deal.II/group__feaccess.html", "group__feaccess" ],
    [ "Finite element space descriptions", "http://www.dealii.org/developer/doxygen/deal.II/group__fe.html", null ],
    [ "Mappings between reference and real cell", "http://www.dealii.org/developer/doxygen/deal.II/group__mapping.html", "group__mapping" ],
    [ "How Mapping, FiniteElement, and FEValues work together", "http://www.dealii.org/developer/doxygen/deal.II/group__FE__vs__Mapping__vs__FEValues.html", null ],
    [ "Functions", "http://www.dealii.org/developer/doxygen/deal.II/group__functions.html", "group__functions" ],
    [ "The geodynamics demonstration suite", "http://www.dealii.org/developer/doxygen/deal.II/group__geodynamics.html", null ],
    [ "Geometric and other primitives", "http://www.dealii.org/developer/doxygen/deal.II/group__geomprimitives.html", null ],
    [ "Grid classes", "http://www.dealii.org/developer/doxygen/deal.II/group__grid.html", "group__grid" ],
    [ "hp finite element support", "http://www.dealii.org/developer/doxygen/deal.II/group__hp.html", null ],
    [ "hp Collections", "http://www.dealii.org/developer/doxygen/deal.II/group__hpcollection.html", null ],
    [ "Integrators", "http://www.dealii.org/developer/doxygen/deal.II/group__Integrators.html", null ],
    [ "Input/Output", "http://www.dealii.org/developer/doxygen/deal.II/group__IO.html", null ],
    [ "Input", "http://www.dealii.org/developer/doxygen/deal.II/group__input.html", "group__input" ],
    [ "Graphical output", "http://www.dealii.org/developer/doxygen/deal.II/group__output.html", "group__output" ],
    [ "Textual output", "http://www.dealii.org/developer/doxygen/deal.II/group__textoutput.html", "group__textoutput" ],
    [ "Iterators on mesh-like containers", "http://www.dealii.org/developer/doxygen/deal.II/group__Iterators.html", "group__Iterators" ],
    [ "Accessor classes of the mesh iterators", "http://www.dealii.org/developer/doxygen/deal.II/group__Accessors.html", "group__Accessors" ],
    [ "Linear algebra classes", "http://www.dealii.org/developer/doxygen/deal.II/group__LAC.html", null ],
    [ "Linear Operators", "http://www.dealii.org/developer/doxygen/deal.II/group__LAOperators.html", "group__LAOperators" ],
    [ "Manifold description for triangulations", "http://www.dealii.org/developer/doxygen/deal.II/group__manifold.html", "group__manifold" ],
    [ "Matrix classes", "http://www.dealii.org/developer/doxygen/deal.II/group__Matrices.html", null ],
    [ "Basic matrices", "http://www.dealii.org/developer/doxygen/deal.II/group__Matrix1.html", null ],
    [ "Memory handling", "http://www.dealii.org/developer/doxygen/deal.II/group__memory.html", null ],
    [ "The MeshWorker interface", "http://www.dealii.org/developer/doxygen/deal.II/group__MeshWorker.html", "group__MeshWorker" ],
    [ "Multilevel support", "http://www.dealii.org/developer/doxygen/deal.II/group__mg.html", "group__mg" ],
    [ "Parallel computing with multiple processors accessing shared memory", "http://www.dealii.org/developer/doxygen/deal.II/group__threads.html", "group__threads" ],
    [ "Numerical algorithms", "http://www.dealii.org/developer/doxygen/deal.II/group__numerics.html", "group__numerics" ],
    [ "Parallel computing", "http://www.dealii.org/developer/doxygen/deal.II/group__Parallel.html", null ],
    [ "PETScWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__PETScWrappers.html", null ],
    [ "Polynomials and polynomial spaces", "http://www.dealii.org/developer/doxygen/deal.II/group__Polynomials.html", null ],
    [ "Preconditioners and Relaxation Operators", "http://www.dealii.org/developer/doxygen/deal.II/group__Preconditioners.html", "group__Preconditioners" ],
    [ "Quadrature formulas", "http://www.dealii.org/developer/doxygen/deal.II/group__Quadrature.html", null ],
    [ "SLEPcWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__SLEPcWrappers.html", null ],
    [ "Linear solver classes", "http://www.dealii.org/developer/doxygen/deal.II/group__Solvers.html", "group__Solvers" ],
    [ "Sparsity patterns", "http://www.dealii.org/developer/doxygen/deal.II/group__Sparsity.html", "group__Sparsity" ],
    [ "TrilinosWrappers", "http://www.dealii.org/developer/doxygen/deal.II/group__TrilinosWrappers.html", "group__TrilinosWrappers" ],
    [ "The interplay of UpdateFlags, Mapping, and FiniteElement in FEValues", "http://www.dealii.org/developer/doxygen/deal.II/group__UpdateFlags.html", null ],
    [ "Utility functions and classes", "http://www.dealii.org/developer/doxygen/deal.II/group__utilities.html", "group__utilities" ],
    [ "Data storage primitives", "http://www.dealii.org/developer/doxygen/deal.II/group__data.html", null ],
    [ "Vector memory management", "http://www.dealii.org/developer/doxygen/deal.II/group__VMemory.html", null ],
    [ "Handling vector valued problems", "http://www.dealii.org/developer/doxygen/deal.II/group__vector__valued.html", null ],
    [ "Vector classes", "http://www.dealii.org/developer/doxygen/deal.II/group__Vectors.html", "group__Vectors" ],
    [ "OpenCASCADE", "http://www.dealii.org/developer/doxygen/deal.II/group__OpenCASCADE.html", null ],
    [ "ParameterGui", "http://www.dealii.org/developer/doxygen/deal.II/group__ParameterGui.html", "group__ParameterGui" ]
];